apiVersion: v1
kind: PersistentVolume
metadata:
  name: billing-db-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: billing-db-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:

    requests:
      storage: 5Gi