apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inventory-db
  labels:
    app: inventory-db
spec:
  serviceName: inventory-db
  replicas: 1
  selector:
    matchLabels:
      app: inventory-db
  template:
    metadata:
      labels:
        app: inventory-db
    spec:
      initContainers:
        - name: mount-permissions-fix
          image: busybox
          command: ["sh", "-c", "chown -R 70:70 /var/lib/pgsql/16/data"]
          volumeMounts:
            - mountPath: /var/lib/pgsql/16/data
              name: data
      containers:
        - name: inventory-db
          image: nekitkas/inventory-db:latest
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: inventory-db-config
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: inventory-db-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: inventory-db-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/pgsql/16/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: inventory-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-db
  labels:
    app: inventory-db
spec:
  ports:
    - name: inventory-db
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: inventory-db
  clusterIP: None
