apiVersion: v1
kind: PersistentVolume
metadata:
  name: inventory-db-pv
spec:
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  capacity:
      storage: 2Gi
  accessModes:
      - ReadWriteOnce
  local:
    path: /local/inventory-db-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ubuntu2204.localdomain